using System.Text.Json.Serialization;
using LucyAPI.Api.Auth;
using LucyAPI.Api.Models;
using LucyAPI.Data.Models;
using LucyAPI.Services.DTOs;

namespace LucyAPI.Api;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(TimeResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(AgentContext))]
// Data models
[JsonSerializable(typeof(Agent))]
[JsonSerializable(typeof(AgentRef))]
[JsonSerializable(typeof(AlwaysLoadItem))]
[JsonSerializable(typeof(AlwaysLoadCreated))]
[JsonSerializable(typeof(Memory))]
[JsonSerializable(typeof(MemoryCreated))]
[JsonSerializable(typeof(Preference))]
[JsonSerializable(typeof(PreferenceTopLevel))]
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(ProjectCreated))]
[JsonSerializable(typeof(ProjectStatus))]
[JsonSerializable(typeof(ProjectSection))]
[JsonSerializable(typeof(SectionCreated))]
[JsonSerializable(typeof(Wiki))]
[JsonSerializable(typeof(WikiCreated))]
[JsonSerializable(typeof(WikiSection))]
[JsonSerializable(typeof(WikiSectionCreated))]
[JsonSerializable(typeof(WikiTagSearchResult))]
[JsonSerializable(typeof(Handoff))]
[JsonSerializable(typeof(HandoffCreated))]
[JsonSerializable(typeof(HandoffPickedUp))]
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(SessionCreated))]
[JsonSerializable(typeof(DeleteResult))]
[JsonSerializable(typeof(MutationResult))]
[JsonSerializable(typeof(Hint))]
[JsonSerializable(typeof(HintCompact))]
[JsonSerializable(typeof(HintCreated))]
[JsonSerializable(typeof(Secret))]
[JsonSerializable(typeof(ShareRecord))]
[JsonSerializable(typeof(ShareCreated))]
[JsonSerializable(typeof(SharePermissionCheck))]
// Lists
[JsonSerializable(typeof(List<AlwaysLoadItem>))]
[JsonSerializable(typeof(List<Memory>))]
[JsonSerializable(typeof(List<PreferenceTopLevel>))]
[JsonSerializable(typeof(List<Preference>))]
[JsonSerializable(typeof(List<Project>))]
[JsonSerializable(typeof(List<ProjectStatus>))]
[JsonSerializable(typeof(List<ProjectSection>))]
[JsonSerializable(typeof(List<Wiki>))]
[JsonSerializable(typeof(List<WikiSection>))]
[JsonSerializable(typeof(List<WikiTagSearchResult>))]
[JsonSerializable(typeof(List<Handoff>))]
[JsonSerializable(typeof(List<Hint>))]
[JsonSerializable(typeof(List<HintCompact>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<ShareRecord>))]
// Tree nodes
[JsonSerializable(typeof(TreeNode<AlwaysLoadItem>))]
[JsonSerializable(typeof(TreeNode<Preference>))]
[JsonSerializable(typeof(TreeNode<ProjectSection>))]
[JsonSerializable(typeof(TreeNode<WikiSection>))]
[JsonSerializable(typeof(TreeNode<Hint>))]
[JsonSerializable(typeof(TreeNode<HintCompact>))]
[JsonSerializable(typeof(List<TreeNode<AlwaysLoadItem>>))]
[JsonSerializable(typeof(List<TreeNode<Preference>>))]
[JsonSerializable(typeof(List<TreeNode<ProjectSection>>))]
[JsonSerializable(typeof(List<TreeNode<WikiSection>>))]
[JsonSerializable(typeof(List<TreeNode<Hint>>))]
[JsonSerializable(typeof(List<TreeNode<HintCompact>>))]
// DTOs (request bodies)
[JsonSerializable(typeof(CreateMemoryRequest))]
[JsonSerializable(typeof(UpdateMemoryRequest))]
[JsonSerializable(typeof(CreatePreferenceRequest))]
[JsonSerializable(typeof(UpdatePreferenceRequest))]
[JsonSerializable(typeof(CreateAlwaysLoadRequest))]
[JsonSerializable(typeof(UpdateAlwaysLoadRequest))]
[JsonSerializable(typeof(CreateProjectRequest))]
[JsonSerializable(typeof(UpdateProjectRequest))]
[JsonSerializable(typeof(CreateSectionRequest))]
[JsonSerializable(typeof(UpdateSectionRequest))]
[JsonSerializable(typeof(CreateWikiRequest))]
[JsonSerializable(typeof(UpdateWikiRequest))]
[JsonSerializable(typeof(CreateWikiSectionRequest))]
[JsonSerializable(typeof(UpdateWikiSectionRequest))]
[JsonSerializable(typeof(CreateHandoffRequest))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(CreateHintCategoryRequest))]
[JsonSerializable(typeof(CreateHintRequest))]
[JsonSerializable(typeof(UpdateHintRequest))]
[JsonSerializable(typeof(SetSecretRequest))]
[JsonSerializable(typeof(ShareObjectRequest))]
// API response wrappers (AOT-safe replacements for anonymous types)
[JsonSerializable(typeof(AgentAlwaysLoadListResponse))]
[JsonSerializable(typeof(AgentMemoryListResponse))]
[JsonSerializable(typeof(AgentPreferenceListResponse))]
[JsonSerializable(typeof(AgentPreferenceTreeResponse))]
[JsonSerializable(typeof(ProjectDetailResponse))]
[JsonSerializable(typeof(ProjectCompactResponse))]
[JsonSerializable(typeof(ProjectCompact))]
[JsonSerializable(typeof(ProjectSectionCompact))]
[JsonSerializable(typeof(List<ProjectSectionCompact>))]
[JsonSerializable(typeof(SecretKeyListResponse))]
[JsonSerializable(typeof(DeleteCountResponse))]
[JsonSerializable(typeof(SectionsDeletedResponse))]
[JsonSerializable(typeof(KeyStatusResponse))]
[JsonSerializable(typeof(StatusResponse))]
[JsonSerializable(typeof(WikiDetailResponse))]
[JsonSerializable(typeof(WikiTagListResponse))]
[JsonSerializable(typeof(TagSearchResponse))]
[JsonSerializable(typeof(BootResponse))]
[JsonSerializable(typeof(BootEndpointMap))]
[JsonSerializable(typeof(BootSaveEndpoint))]
// Project 38: Nudges
[JsonSerializable(typeof(Nudge))]
[JsonSerializable(typeof(NudgeCreated))]
[JsonSerializable(typeof(ActionableNudge))]
[JsonSerializable(typeof(List<Nudge>))]
[JsonSerializable(typeof(List<ActionableNudge>))]
[JsonSerializable(typeof(CreateNudgeRequest))]
[JsonSerializable(typeof(UpdateNudgeRequest))]
[JsonSerializable(typeof(NudgeListResponse))]
[JsonSerializable(typeof(AdminCreatedResponse<NudgeCreated>))]
// Phase 5: Google Docs
[JsonSerializable(typeof(DocResponse))]
[JsonSerializable(typeof(DriveFileInfo))]
[JsonSerializable(typeof(DriveFileListResponse))]
[JsonSerializable(typeof(FolderResponse))]
[JsonSerializable(typeof(MoveFileResponse))]
[JsonSerializable(typeof(DeleteFileResponse))]
[JsonSerializable(typeof(CreateDocRequest))]
[JsonSerializable(typeof(UpdateDocRequest))]
[JsonSerializable(typeof(AppendDocRequest))]
[JsonSerializable(typeof(CreateFolderRequest))]
[JsonSerializable(typeof(MoveFileRequest))]
[JsonSerializable(typeof(List<DriveFileInfo>))]
// Phase 5: Images
[JsonSerializable(typeof(ImageRecord))]
[JsonSerializable(typeof(ImageDeleteResult))]
[JsonSerializable(typeof(ImageResponse))]
[JsonSerializable(typeof(ImageDeleteResponse))]
[JsonSerializable(typeof(ImageCleanupResponse))]
[JsonSerializable(typeof(AnalyzeImageResponse))]
[JsonSerializable(typeof(GenImageRequest))]
[JsonSerializable(typeof(EditImageRequest))]
[JsonSerializable(typeof(AnalyzeImageRequest))]
[JsonSerializable(typeof(KeepImageRequest))]
[JsonSerializable(typeof(List<ImageResponse>))]
// Phase 5: Save Notes
[JsonSerializable(typeof(SaveNotesRequest))]
[JsonSerializable(typeof(SaveNotesResponse))]
// Admin: Auth
[JsonSerializable(typeof(UserContext))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(ChangePasswordRequest))]
[JsonSerializable(typeof(UserInfoResponse))]
[JsonSerializable(typeof(OkResponse))]
[JsonSerializable(typeof(User))]
// Admin: Agent list
[JsonSerializable(typeof(AdminAgentItem))]
[JsonSerializable(typeof(AdminLastSession))]
[JsonSerializable(typeof(AdminAgentListResponse))]
[JsonSerializable(typeof(List<AdminAgentItem>))]
// Admin: Agent-scoped responses
[JsonSerializable(typeof(AdminCreatedResponse<AlwaysLoadCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<MemoryCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<HandoffCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<MutationResult>))]
[JsonSerializable(typeof(AdminCreatedResponse<ProjectCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<SectionCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<WikiCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<WikiSectionCreated>))]
[JsonSerializable(typeof(AdminCreatedResponse<HintCreated>))]
[JsonSerializable(typeof(AdminUpdatedResponse<MutationResult>))]
[JsonSerializable(typeof(AdminUpdatedResponse<ProjectCreated>))]
[JsonSerializable(typeof(AdminUpdatedResponse<SectionCreated>))]
[JsonSerializable(typeof(AdminUpdatedResponse<WikiCreated>))]
[JsonSerializable(typeof(AdminUpdatedResponse<WikiSectionCreated>))]
[JsonSerializable(typeof(AdminUpdatedResponse<AdminShareCreatedItem>))]
[JsonSerializable(typeof(AdminDeletedResponse))]
[JsonSerializable(typeof(AdminDeletedIdResponse))]
[JsonSerializable(typeof(AdminDeletedKeyResponse))]
[JsonSerializable(typeof(AdminMemoryListResponse))]
[JsonSerializable(typeof(AdminHandoffListResponse))]
[JsonSerializable(typeof(AdminSessionLastResponse))]
[JsonSerializable(typeof(AdminPickedUpResponse))]
[JsonSerializable(typeof(AdminPickedUpItem))]
// Admin: Resource responses
[JsonSerializable(typeof(AdminProjectStatusListResponse))]
[JsonSerializable(typeof(AdminSectionsDeletedResponse))]
[JsonSerializable(typeof(AdminWikiTagListResponse))]
[JsonSerializable(typeof(AdminSecretListResponse))]
[JsonSerializable(typeof(AdminSecretKey))]
[JsonSerializable(typeof(List<AdminSecretKey>))]
[JsonSerializable(typeof(AdminSecretValueResponse))]
[JsonSerializable(typeof(AdminUserListResponse))]
[JsonSerializable(typeof(List<UserInfoResponse>))]
[JsonSerializable(typeof(AdminShareListResponse))]
[JsonSerializable(typeof(AdminShareItem))]
[JsonSerializable(typeof(List<AdminShareItem>))]
[JsonSerializable(typeof(AdminShareCreateRequest))]
[JsonSerializable(typeof(AdminShareUpdateRequest))]
[JsonSerializable(typeof(AdminShareCreatedResponse))]
[JsonSerializable(typeof(AdminShareCreatedItem))]
[JsonSerializable(typeof(AdminRevokedResponse))]
[JsonSerializable(typeof(AdminKeepRequest))]
// Admin: Dashboard
[JsonSerializable(typeof(AdminDashboardResponse))]
[JsonSerializable(typeof(AdminDashboardStats))]
[JsonSerializable(typeof(AdminRecentSession))]
[JsonSerializable(typeof(List<AdminRecentSession>))]
// System types
[JsonSerializable(typeof(System.Text.Json.JsonDocument))]
[JsonSerializable(typeof(string[]))]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}
