using System.Text.Json.Serialization;
using LucyAPI.Api.Models;
using LucyAPI.Data.Models;
using LucyAPI.Services.DTOs;

namespace LucyAPI.Api;

[JsonSerializable(typeof(HealthResponse))]
[JsonSerializable(typeof(TimeResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(AgentContext))]
// Data models
[JsonSerializable(typeof(Agent))]
[JsonSerializable(typeof(AgentRef))]
[JsonSerializable(typeof(AlwaysLoadItem))]
[JsonSerializable(typeof(AlwaysLoadCreated))]
[JsonSerializable(typeof(Memory))]
[JsonSerializable(typeof(MemoryCreated))]
[JsonSerializable(typeof(Preference))]
[JsonSerializable(typeof(PreferenceTopLevel))]
[JsonSerializable(typeof(Project))]
[JsonSerializable(typeof(ProjectCreated))]
[JsonSerializable(typeof(ProjectStatus))]
[JsonSerializable(typeof(ProjectSection))]
[JsonSerializable(typeof(SectionCreated))]
[JsonSerializable(typeof(Wiki))]
[JsonSerializable(typeof(WikiCreated))]
[JsonSerializable(typeof(WikiSection))]
[JsonSerializable(typeof(WikiSectionCreated))]
[JsonSerializable(typeof(WikiTagSearchResult))]
[JsonSerializable(typeof(Handoff))]
[JsonSerializable(typeof(HandoffCreated))]
[JsonSerializable(typeof(HandoffPickedUp))]
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(SessionCreated))]
[JsonSerializable(typeof(DeleteResult))]
[JsonSerializable(typeof(MutationResult))]
[JsonSerializable(typeof(Hint))]
[JsonSerializable(typeof(HintCompact))]
[JsonSerializable(typeof(HintCreated))]
[JsonSerializable(typeof(Secret))]
[JsonSerializable(typeof(ShareRecord))]
[JsonSerializable(typeof(ShareCreated))]
[JsonSerializable(typeof(SharePermissionCheck))]
// Lists
[JsonSerializable(typeof(List<AlwaysLoadItem>))]
[JsonSerializable(typeof(List<Memory>))]
[JsonSerializable(typeof(List<PreferenceTopLevel>))]
[JsonSerializable(typeof(List<Preference>))]
[JsonSerializable(typeof(List<Project>))]
[JsonSerializable(typeof(List<ProjectStatus>))]
[JsonSerializable(typeof(List<ProjectSection>))]
[JsonSerializable(typeof(List<Wiki>))]
[JsonSerializable(typeof(List<WikiSection>))]
[JsonSerializable(typeof(List<WikiTagSearchResult>))]
[JsonSerializable(typeof(List<Handoff>))]
[JsonSerializable(typeof(List<Hint>))]
[JsonSerializable(typeof(List<HintCompact>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<ShareRecord>))]
// Tree nodes
[JsonSerializable(typeof(TreeNode<AlwaysLoadItem>))]
[JsonSerializable(typeof(TreeNode<Preference>))]
[JsonSerializable(typeof(TreeNode<ProjectSection>))]
[JsonSerializable(typeof(TreeNode<WikiSection>))]
[JsonSerializable(typeof(TreeNode<Hint>))]
[JsonSerializable(typeof(TreeNode<HintCompact>))]
[JsonSerializable(typeof(List<TreeNode<AlwaysLoadItem>>))]
[JsonSerializable(typeof(List<TreeNode<Preference>>))]
[JsonSerializable(typeof(List<TreeNode<ProjectSection>>))]
[JsonSerializable(typeof(List<TreeNode<WikiSection>>))]
[JsonSerializable(typeof(List<TreeNode<Hint>>))]
[JsonSerializable(typeof(List<TreeNode<HintCompact>>))]
// DTOs (request bodies)
[JsonSerializable(typeof(CreateMemoryRequest))]
[JsonSerializable(typeof(UpdateMemoryRequest))]
[JsonSerializable(typeof(CreatePreferenceRequest))]
[JsonSerializable(typeof(UpdatePreferenceRequest))]
[JsonSerializable(typeof(CreateAlwaysLoadRequest))]
[JsonSerializable(typeof(UpdateAlwaysLoadRequest))]
[JsonSerializable(typeof(CreateProjectRequest))]
[JsonSerializable(typeof(UpdateProjectRequest))]
[JsonSerializable(typeof(CreateSectionRequest))]
[JsonSerializable(typeof(UpdateSectionRequest))]
[JsonSerializable(typeof(CreateWikiRequest))]
[JsonSerializable(typeof(UpdateWikiRequest))]
[JsonSerializable(typeof(CreateWikiSectionRequest))]
[JsonSerializable(typeof(UpdateWikiSectionRequest))]
[JsonSerializable(typeof(CreateHandoffRequest))]
[JsonSerializable(typeof(CreateSessionRequest))]
[JsonSerializable(typeof(CreateHintCategoryRequest))]
[JsonSerializable(typeof(CreateHintRequest))]
[JsonSerializable(typeof(UpdateHintRequest))]
[JsonSerializable(typeof(SetSecretRequest))]
[JsonSerializable(typeof(ShareObjectRequest))]
// API response wrappers (AOT-safe replacements for anonymous types)
[JsonSerializable(typeof(AgentAlwaysLoadListResponse))]
[JsonSerializable(typeof(AgentMemoryListResponse))]
[JsonSerializable(typeof(AgentPreferenceListResponse))]
[JsonSerializable(typeof(ProjectDetailResponse))]
[JsonSerializable(typeof(SecretKeyListResponse))]
[JsonSerializable(typeof(DeleteCountResponse))]
[JsonSerializable(typeof(SectionsDeletedResponse))]
[JsonSerializable(typeof(KeyStatusResponse))]
[JsonSerializable(typeof(StatusResponse))]
[JsonSerializable(typeof(WikiDetailResponse))]
[JsonSerializable(typeof(WikiTagListResponse))]
[JsonSerializable(typeof(TagSearchResponse))]
// System types
[JsonSerializable(typeof(System.Text.Json.JsonDocument))]
[JsonSerializable(typeof(string[]))]
public partial class AppJsonSerializerContext : JsonSerializerContext
{
}
