-- oauth_clients.sql
-- OAuth 2.1 clients allowed to request tokens for the LucyAPI MCP connector.
-- Two registration paths:
--   'dcr'  — Dynamic Client Registration (RFC 7591): client_id is generated by LucyAPI.
--   'cimd' — Client ID Metadata Document: client_id IS an https URL whose JSON document
--            declares the client's redirect_uris; cached here after fetching.
-- All clients are public (PKCE, no client secret).

CREATE TABLE IF NOT EXISTS oauth_clients (
    client_id           TEXT            PRIMARY KEY,
    registration_type   TEXT            NOT NULL CHECK (registration_type IN ('dcr', 'cimd')),
    client_name         TEXT            NULL,
    redirect_uris       TEXT[]          NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    metadata_fetched_at TIMESTAMPTZ     NULL,
    last_used_at        TIMESTAMPTZ     NULL
);
